# docker profile：容器内用服务名访问同网络容器
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/seckill?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true

seckill:
  redis:
    master: redis-master:6379
    replicas: redis-replica-1:6379,redis-replica-2:6379
  kafka:
    bootstrap: kafka:29092
